[workspace]
resolver = "2"
members = [
    "./cmd/skate",
    "./cmd/skate-treewalk",
    "./crates/compiler",
    "./crates/diagnostics",
    "./crates/parser",
    "./crates/rt_common",
    "./crates/treewalk",
    "./crates/value",
    "./crates/vm",
    "./playground",
    "./tests/runner",
]
