on:
  push:
    branches:
      - trunk
  # workflow_dispatch:
  #   inputs:
  #     debug_enabled:
  #       description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
  #       required: false
  #       default: false

name: Build Site

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      # TODO: Maybe use https://github.com/actions-rs/install when its ready 
      # - run: cargo install wasm-pack just
      - run: ./scripts/ci.sh
      # - run: pwd; ls
      # - uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - run: ./scripts/site.sh
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true
