on:
  push:
    branches:
      - trunk

name: Build Site

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      # TODO: Maybe use https://github.com/actions-rs/install when its ready 
      # - run: cargo install wasm-pack just
      - run: source ./scripts/ci.sh
      - run: pwd; ls
      - run: just wasm
      - run: mv playground/static public
      - run: rm public/.gitignore
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true